config/routes.rb
Devi::Application.routes.draw do
resources :users, only: [:index]

resources :activities

resources :stories do
 resources :comments, :tasks
  get :icebox, :current, :backlog, :done, on: :member
end

  resources :projects do
    resources :members, :stories
  end

  get "static_pages/home"
  get "static_pages/help"

  devise_for :users, controllers: {confirmations: 'confirmations', passwords: 'passwords', }
  devise_scope :user do
    get '/help' => 'static_pages#help', as: 'confirmation_getting_started'
  end

  root 'static_pages#help'
  match '/help', to: 'static_pages#help', via: 'get'
  get "projects/:id_project/members/:id/activate" => "members#activate", :as => "active_member"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :authenticate_user!, only: :help
  before_filter :redirect_user, only: :help

  def home
  end

  def help
  end

  private
  def redirect_user
    if current_user.present?
      redirect_to projects_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/static_pages/help.html.erb
<div class="well">
  <h1>Welcome to bugzilla</h1>

  <div class="modal-body row-fluid">
    <div class="span6">
      <!-- Your first column here -->
      <h5>Sign up</h5>

      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div><%= f.label :email %>
            <br/>
            <%= f.email_field :email, :autofocus => true %></div>

          <div><%= f.label :password %>
            <br/>
            <%= f.password_field :password %></div>

          <div><%= f.label :password_confirmation %>
            <br/>
            <%= f.password_field :password_confirmation %></div>

          <div><%= f.submit "Create my account", class: "btn btn-large btn-primary" %></div>
      <% end %>


    </div>
    <div class="span6">
      <h5>Sign in</h5>
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div><%= f.label :email %>
            <br/>
            <%= f.email_field :email %></div>

          <div><%= f.label :password %>
            <br/>
            <%= f.password_field :password %></div>

          <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              <%= link_to "Forgot your password?", new_password_path(resource_name) %>
              <br/>
          <% end -%>
          <div><%= f.submit "Login", class: "btn btn-large btn-primary" %></div>
      <% end %>


    </div>
  </div>
</div>