config/routes.rb
Devi::Application.routes.draw do
resources :users, only: [:index]

resources :activities

resources :stories do
 resources :comments, :tasks
  get :icebox, :current, :backlog, :done, on: :member
end

  resources :projects do
    resources :members, :stories
  end

  get "static_pages/home"
  get "static_pages/help"

  devise_for :users, controllers: {confirmations: 'confirmations', passwords: 'passwords', }
  devise_scope :user do
    get '/help' => 'static_pages#help', as: 'confirmation_getting_started'
  end

  root 'static_pages#help'
  match '/help', to: 'static_pages#help', via: 'get'
  get "projects/:id_project/members/:id/activate" => "members#activate", :as => "active_member"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
  has_many :members,->{order(member_name: :asc)}, :dependent => :destroy
  has_many :stories, :dependent => :destroy

  after_create :create_member
  attr_accessible :name, :user_name
  attr_accessor :current_user_email
  validates :name, :user_name, presence: true
  validates :name, uniqueness: true
  validates_length_of :name, maximum: 15
  default_scope ->{ order(updated_at: :desc) }

  def create_member
    Member.create!(member_name: current_user_email, email_member: current_user_email, project_id: id, project_owner: true, confirmed: true)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]


  def index
    @projects = Project.joins(:members).where('lower(members.email_member) = ? AND confirmed = true', current_user.email.downcase).uniq.page(params[:page]).per(8)
  end

  def show
  end

  def new
    @project = Project.new

  end


  def edit

  end


  def create
    @project = Project.new(params[:project])
    @project.current_user_email = current_user.email
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }

      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :user_name)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.hidden_field :user_name, :value => current_user.email %>
    </div>
    <div class="clickable" url="http://google.com">
      blah blah
    </div>
    <div class="actions">
      <%= f.submit "SAVE", :class => "btn btn-success" %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Add / Edit Project</h1>


<%= render 'form' %>

<div class="field">
  <%= link_to "Add new member to Project", new_project_member_path(@project), :class => "btn btn-primary" %></br>
  <b>Members:</b></br>

  <% @project.members.each do |f| %>

      <% if f.confirmed.nil? %>
          <div class="nacc">
            <ul>
              <li><%= link_to f.member_name, edit_project_member_path(@project, f), {:style => 'color:RED;'} %>
                <%= link_to "x", [@project, f], :method => :delete, data: {confirm: 'Are you sure?'} %>
                </br>
              </li>
            </ul>
          </div>
      <% else %>
          <div class="acc">
            <ul>
              <li><%= link_to f.member_name, edit_project_member_path(@project, f), {:style => 'color:GREEN;'} %>
                <%= link_to "x", [@project, f], :method => :delete, data: {confirm: 'Are you sure?'} %>
                </br>
              </li>
            </ul>
          </div>
      <% end %>
  <% end %>
  </br>


</div>


<%= link_to 'Cancel', projects_path, class: "btn btn-danger" %>

app/views/projects/index.html.erb
<h1>Dashboard Projects</h1>
<%= button_to "Add new project", new_project_path, :method => "get", class: "btn btn-primary" %>
<div class="row">

  <% @projects.each do |project| %>
      <div class="pull-left" id="pro">
        <%= link_to edit_project_path(project) do %>
        <div class="well">
          <div class="caption">
            <p><%= link_to project.name, project_path(project), :class => "btn btn-warning" %></p>

            <p>

              <% project.activities.limit(3).order("created_at desc").each do |activity| %>
                  <%= activity.text(owner: activity.owner.email) %>
                <hr>
            <% end %>
            </p>

            <p class="pull-centre">
              <%= link_to "Edit", edit_project_path(project), :class => "btn btn-success" %>
              <%= link_to "Delete", project, method: :delete, data: {confirm: "Are you sure you want to delete #{project.name} ?"}, :class => "btn btn-danger" %>
            </p>
          </div>

        </div>
        <% end %>
      </div>


  <% end %>

</div>


<footer class="center"><%= paginate @projects %></footer>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.name %>
</p>
<hr>

<%= link_to 'Current', current_story_path(@project), :class => "btn btn-success" %>
<%= link_to 'Backlog', backlog_story_path(@project), :class => "btn btn-success" %>
<%= link_to 'Icebox', icebox_story_path(@project), :class => "btn btn-success" %>
<%= link_to 'Add new Story', new_project_story_path(@project), :class => "btn btn-primary" %>
<%= link_to 'Back to The Dashboard', projects_path, :class => "btn btn-danger" %>
<%= link_to 'Done', done_story_path(@project), :class => "btn btn-warning" %>