config/routes.rb
Devi::Application.routes.draw do
resources :users, only: [:index]

resources :activities

resources :stories do
 resources :comments, :tasks
  get :icebox, :current, :backlog, :done, on: :member
end

  resources :projects do
    resources :members, :stories
  end

  get "static_pages/home"
  get "static_pages/help"

  devise_for :users, controllers: {confirmations: 'confirmations', passwords: 'passwords', }
  devise_scope :user do
    get '/help' => 'static_pages#help', as: 'confirmation_getting_started'
  end

  root 'static_pages#help'
  match '/help', to: 'static_pages#help', via: 'get'
  get "projects/:id_project/members/:id/activate" => "members#activate", :as => "active_member"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/story.rb
class Story < ActiveRecord::Base

  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  validates :status, inclusion: {in: %w(Unstarted Started Finished Delivered Accepted Rejected)}
  belongs_to :project
  has_many :comments, -> {order(created_at: :desc)}
  has_many :tasks, -> {order(created_at: :desc)}
  attr_accessible :project_id, :name, :status, :owner, :story_type, :description, :select
  validates :project_id, :name, :status, :owner, :story_type, :description, :select, presence: true
  validates_length_of :name, maximum: 15
  validates :name, uniqueness: {scope: :project_id}
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_filter :find_story, :only => [:done, :current, :icebox, :backlog, :index]

  def done
  end

  def current
  end

  def backlog
  end

  def icebox
  end

  def index
  end

  def show
    @project = Project.find(params[:project_id])
    @story = @project.stories.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @story = @project.stories.build
  end

  def edit
    @project = Project.find(params[:project_id])
    @story = @project.stories.find(params[:id])
  end


  def create
    @project = Project.find(params[:project_id])
    @story = @project.stories.create(params[:story])
    if @story.save
      @project.create_activity key: 'project.new_story', owner: current_user
      redirect_to project_path(@project)
    else
      render "new"
    end


  end

  def update
    @project = Project.find(params[:project_id])
    @story = @project.stories.find(params[:id])


    if @story.update_attributes(params[:story])
      redirect_to(:back, :notice => 'Stories was successfully updated.')

    else
      render :action => "edit"

    end
  end


  def destroy
    @project = Project.find(params[:project_id])

    @story = @project.stories.find(params[:id])
    @story.destroy

    redirect_to(:back)
  end

  private
  def find_story
    @project = Project.find(params[:id])
    @stories = @project.stories
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_story
    @story = Story.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def story_params
    params.require(:story).permit(:name, :project_id, :status, :description, :story_type, :owner)
  end

  def get_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def status_button(story)
    links = case story.status
              when 'Unstarted'
                [{
                     status: 'Started',
                     col: 'default'
                 }]
              when 'Started'
                [{
                     status: 'Finished',
                     col: 'primary'
                 }]
              when 'Finished'
                [{
                     status: 'Delivered',
                     col: 'warning'
                 }]
              when 'Delivered'
                [{
                     status: 'Accepted',
                     col: 'success'
                 },
                 {
                     status: 'Rejected',
                     col: 'danger'
                 }]
              when 'Rejected'
                [{
                     status: 'Unstarted',
                     col: 'default'
                 }]
            end
    links.each_with_object([]) do |link, obj|
      obj << link_to(link[:status], project_story_path(story.project, story, story: {status: link[:status]}), method: "put", :class => "btn btn-#{link[:col]}")

    end.join("").html_safe
  end
end

app/views/stories/_buttons.html.erb
<%= link_to 'Current', current_story_path(@project), :class => "btn btn-success" %>
<%= link_to 'Backlog', backlog_story_path(@project), :class => "btn btn-success" %>
<%= link_to 'Icebox', icebox_story_path(@project), :class => "btn btn-success" %>
<%= link_to 'Add new Story', new_project_story_path(@project), :class => "btn btn-primary" %>
<%= link_to 'Back to The Dashboard', projects_path, :class => "btn btn-danger" %>
<%= link_to 'Done', done_story_path(@project), :class => "btn btn-warning" %>
<br>
<br>
<br>
<br>

app/views/stories/_form.html.erb
<%= form_for([@project, @story]) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

          <ul>
            <% @story.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.hidden_field :project_id %>
    </div>
    <% if @story.status != 'Accepted' %>
        <div class="field">
          <%= f.select :status, ['Unstarted', 'Started', 'Finished', 'Delivered', 'Accepted', 'Rejected'] %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :description %>
      <br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :story_type %>
      <br>
      <%= f.select :story_type, ['Feature', 'Bug', 'Chore', 'Release'] %>
    </div>
    <div class="field">
      <%= f.label :owner %>
      <br>
      <%= f.select(:owner, @project.members.map { |d| [d.member_name] }) %>

    </div>
    <div class="field">
      <%= f.label :select %>
      <br>
      <%= f.select(:select, ['Icebox', 'Backlog']) %>
    </div>

    <div class="actions">
      <%= f.submit :class => "btn btn-success" %>
    </div>
<% end %>

app/views/stories/backlog.html.erb
<h1>Backlog</h1>

<%= render 'buttons' %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Story type</th>
    <th>Owner</th>
    <th>Comments</th>
    <th>Tasks</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>

  <% @stories.each do |story| %>
      <% if story.select == 'Backlog' && story.status == 'Unstarted' %>
          <tr>
            <td><%= link_to story.name, edit_project_story_path(story.project, story) %></td>
            <td><%= story.status %></td>
            <td><%= story.story_type %></td>
            <td><%= story.owner %></td>
            <td><%= story.comments.size %></td>
            <td><%= story.tasks.size %></td>
            <td><%= status_button(story) %></td>
            <td><%= link_to 'x', [story.project, story], method: :delete %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/stories/current.html.erb
<h1>Current</h1>

<%= render 'buttons' %>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Story type</th>
    <th>Owner</th>
    <th>Comments</th>
    <th>Tasks</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>

  <% @stories.each do |story| %>
      <% if story.status != 'Unstarted' && story.status != 'Accepted' %>
          <tr>
            <td><%= link_to story.name, edit_project_story_path(story.project, story) %></td>
            <td><%= story.status %></td>
            <td><%= story.story_type %></td>
            <td><%= story.owner %></td>
            <td><%= story.comments.size %></td>
            <td><%= story.tasks.size %></td>
            <td><%= status_button(story) %></td>
            <td><%= link_to 'x', [story.project, story], method: :delete %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/stories/done.html.erb
<h1>Done</h1>

<%= render 'buttons' %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Story type</th>
    <th>Owner</th>
    <th>Comments</th>
    <th>Tasks</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>

  <% @stories.each do |story| %>
      <% if story.status == 'Accepted' %>
          <tr>
            <td><%= link_to story.name, edit_project_story_path(story.project, story) %></td>
            <td><%= story.status %></td>
            <td><%= story.story_type %></td>
            <td><%= story.owner %></td>
            <td><%= story.comments.size %></td>
            <td><%= story.tasks.size %></td>
            <td><%= link_to 'x', [story.project, story], method: :delete %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<div class="field">
  <%= link_to "Add new Comment", new_story_comment_path(@story), :class => "btn btn-primary" %>
  <br>
</div>
<h2>Comments</h2>
<% @story.comments.each do |comment| %>
    <p>User: <%= comment.user.email %></p>
    <br>
    <p>Comment: <%= comment.body %> </p>
    <%= link_to "Delete", [@story, comment], :method => :delete %>
    <hr>
<% end %>
<div class="field">
  <%= link_to "Add new Task", new_story_task_path(@story), :class => "btn btn-warning" %>
  <br>
</div>
<h2>Tasks</h2>
<% @story.tasks.each do |task| %>
    <p>User: <%= task.user.email %></p>
    <br>
    <p>Task: <%= task.task_field %> </p>
    <%= link_to "Delete", [@story, task], :method => :delete %>
    <hr>
<% end %>
<%= link_to 'Cancel', project_path(@project), :class => "btn btn-danger" %>

app/views/stories/icebox.html.erb
<h1>Icebox</h1>

<%= render 'buttons' %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Story type</th>
    <th>Owner</th>
    <th>Comments</th>
    <th>Tasks</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>

  <% @stories.each do |story| %>
      <% if story.select == 'Icebox' && story.status == 'Unstarted' %>
          <tr>
            <td><%= link_to story.name, edit_project_story_path(story.project, story) %></td>
            <td><%= story.status %></td>
            <td><%= story.story_type %></td>
            <td><%= story.owner %></td>
            <td><%= story.comments.size %></td>
            <td><%= story.tasks.size %></td>
            <td><%= link_to 'x', [story.project, story], method: :delete %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Project</th>
    <th>Status</th>
    <th>Description</th>
    <th>Story type</th>
    <th>Owner</th>
    <th>Select</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @stories.each do |story| %>
      <tr>
        <td><%= story.name %></td>
        <td><%= story.project_id %></td>
        <td><%= story.status %></td>
        <td><%= story.description %></td>
        <td><%= story.story_type %></td>
        <td><%= story.owner %></td>
        <td><%= story.select %></td>

        <td><%= link_to 'Show', [story.project, story] %></td>
        <td><%= link_to 'Edit', edit_project_story_path(story.project, story) %></td>
        <td><%= link_to 'Destroy', [story.project, story], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_project_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Cancel', project_path(@project), :class => "btn btn-danger" %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @story.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @story.project_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @story.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Story type:</strong>
  <%= @story.story_type %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @story.owner %>
</p>

<%= link_to 'Edit', edit_project_story_path(@project, @story) %> |
<%= link_to 'Back', project_path(@project) %>