config/routes.rb
Devi::Application.routes.draw do
resources :users, only: [:index]

resources :activities

resources :stories do
 resources :comments, :tasks
  get :icebox, :current, :backlog, :done, on: :member
end

  resources :projects do
    resources :members, :stories
  end

  get "static_pages/home"
  get "static_pages/help"

  devise_for :users, controllers: {confirmations: 'confirmations', passwords: 'passwords', }
  devise_scope :user do
    get '/help' => 'static_pages#help', as: 'confirmation_getting_started'
  end

  root 'static_pages#help'
  match '/help', to: 'static_pages#help', via: 'get'
  get "projects/:id_project/members/:id/activate" => "members#activate", :as => "active_member"


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/member.rb
class Member < ActiveRecord::Base

  attr_accessible :project_id, :member_name, :email_member, :project_owner, :confirmed
  validates_presence_of :member_name, :email_member, :project_id
  validates :project_owner, :inclusion => {:in => [true, false]}
  belongs_to :project

  before_create :generate_token

  def activate!(current_user)

    if current_user && current_user.email.downcase == email_member.downcase
      update_attribute(:confirmed, true)
    else
      raise "Invalid user"
    end
  end

  private


  def generate_token
    self.confirmation_token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  #before_filter :get_project
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def activate
    @project = Project.find(params[:id_project])
    @member = @project.members.find(params[:id])

    @member.activate!(current_user)
    redirect_to root_path

  end

  def index

    project = Project.find(params[:project_id])

    @members = project.members

    respond_to do |format|
      format.html
      format.xml { render :xml => @members }
    end
  end

  def show
    @project = Project.find(params[:project_id])
    @member = @project.members.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # GET /members/new
  def new

    @project = Project.find(params[:project_id])
    @member = @project.members.build

    respond_to do |format|
      format.html
      format.xml { render :xml => @member }
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @member = @project.members.find(params[:id])
  end

  def create
    @project = Project.find(params[:project_id])
    @member = @project.members.create(params[:member])

    respond_to do |format|
      if @member.save
        UserMailer.confirm_email(@project, @member, @member.confirmation_token).deliver
        format.html { redirect_to(edit_project_path(@project), :notice => "New member was added to #{@project.name}") }
        format.xml { render :xml => @member, :status => :created, :location => [@member.project, @member] }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @member = @project.members.find(params[:id])


    if @member.update_attributes(params[:member])
      redirect_to([@member.project, @member], :notice => 'Comment was successfully updated.')

    else
      render :action => "edit"

    end
  end


  def destroy

    @project = Project.find(params[:project_id])

    @member = @project.members.find(params[:id])
    @member.destroy

    redirect_to edit_project_path(@project)

  end

  private


  def set_member
    @member = Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:project_id, :member_name, :email_member, :project_owner, :confirmed)
  end

  def get_project
    @project = Project.find(params[:project_id])
  end


end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for([@project, @member]) do |f| %>
    <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

          <ul>
            <% @member.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">

      <%= f.label :member_name %>
      <br>
      <%= f.text_field :member_name %>

    </div>
    <div class="field">

      <%= f.label :email_member %>
      <br>
      <%= f.email_field :email_member %>
    </div>

    <div class="field">
      <%= f.label :project_owner %>
      <%= f.check_box :project_owner %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>
<%= link_to 'Back', edit_project_path(@project) %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>


<%= link_to 'Back', project_member_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <thead>
  <tr>
    <th>Member name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @members.each do |member| %>
      <tr>
        <td><%= member.member_name %></td>
        <td><%= link_to 'Show', [member.project, member] %></td>
        <td><%= link_to 'Edit', edit_project_member_path(member.project, member) %></td>
        <td><%= link_to 'Destroy', [member.project, member], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member name:</strong>
  <%= @member.member_name %>
</p>


<%= link_to 'Back', edit_project_path(@project) %>